prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>

SELECT DISTINCT ?obj ?museum ?text ?technique
WHERE {
  GRAPH ?museum {
     ?dig a crmdig:D1_Digital_Object . }
  
      ?dig ecrm:P129_is_about ?prod .
      ?prod ecrm:P108_has_produced ?obj .
      ?obj a ecrm:E22_Man-Made_Object .

      ?obj rdfs:comment ?text .


       ?prod ecrm:P32_used_general_technique ?technique .

                FILTER ((?technique = <http://data.silknow.org/vocabulary/103>) ||

                        (?technique = <http://data.silknow.org/vocabulary/168>) ||

                        (?technique = <http://data.silknow.org/vocabulary/192>) ||

                        (?technique = <http://data.silknow.org/vocabulary/236>) ||


                        (?technique = <http://data.silknow.org/vocabulary/238>) ||


                        (?technique = <http://data.silknow.org/vocabulary/305>) ||


                        (?technique = <http://data.silknow.org/vocabulary/366>) ||


                        (?technique = <http://data.silknow.org/vocabulary/379>) ||


                        (?technique = <http://data.silknow.org/vocabulary/87>))
               

FILTER (?museum = <http://data.silknow.org/graph/joconde> || 
        ?museum = <http://data.silknow.org/graph/mad> || 
        ?museum = <http://data.silknow.org/graph/mtmad> || 
        ?museum = <http://data.silknow.org/graph/versailles> || 
        ?museum = <http://data.silknow.org/graph/paris-musees> || 
        ?museum = <http://data.silknow.org/graph/mobilier> )


}
ORDER BY ?museum
