prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>

SELECT DISTINCT ?obj ?museum ?text ?visual_item
WHERE {
  GRAPH ?museum {
      ?prod ecrm:P108_has_produced ?obj .
      ?obj a ecrm:E22_Man-Made_Object . }
 

      ?obj rdfs:comment ?text .


       ?obj ecrm:P65_shows_visual_item ?visual_item .

                 FILTER ((?visual_item = <http://data.silknow.org/vocabulary/743>) ||

                        (?visual_item = <http://data.silknow.org/vocabulary/744>) ||

                        (?visual_item = <http://data.silknow.org/vocabulary/745>) ||

                        (?visual_item = <http://data.silknow.org/vocabulary/747>) ||


                        (?visual_item = <http://data.silknow.org/vocabulary/761>) ||


                        (?visual_item = <http://data.silknow.org/vocabulary/818>))
               

FILTER (?museum = <http://data.silknow.org/graph/joconde> || 
        ?museum = <http://data.silknow.org/graph/mad> || 
        ?museum = <http://data.silknow.org/graph/mtmad> || 
        ?museum = <http://data.silknow.org/graph/versailles> || 
        ?museum = <http://data.silknow.org/graph/paris-musees> || 
        ?museum = <http://data.silknow.org/graph/mobilier> )


}
ORDER BY ?museum
