prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>

SELECT DISTINCT ?obj ?museum ?text ?material
WHERE {
  GRAPH ?museum {
     ?dig a crmdig:D1_Digital_Object . }
  
      ?dig ecrm:P129_is_about ?prod .
      ?prod ecrm:P108_has_produced ?obj .
      ?obj a ecrm:E22_Man-Made_Object .

      ?obj rdfs:comment ?text .


       ?prod ecrm:P126_employed ?material . 

                FILTER (
                    

                        (?material = <http://data.silknow.org/vocabulary/627>) || 
                        (?material = <http://data.silknow.org/vocabulary/628>) || 
                        (?material = <http://data.silknow.org/vocabulary/214>))


FILTER (contains(str(?museum), "vam") || 
        contains(str(?museum), "risd") || 
        contains(str(?museum), "artic") || 
        contains(str(?museum), "met") || 
        contains(str(?museum), "mfa") || 
        contains(str(?museum), "smithsonian") )


}
ORDER BY ?museum
