prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>

SELECT DISTINCT ?obj ?museum ?text ?visual_item
WHERE {
  GRAPH ?museum {
      ?obj ecrm:P65_shows_visual_item ?visual_item .}
  
   
      ?prod ecrm:P108_has_produced ?obj .
      ?obj a ecrm:E22_Man-Made_Object .

      ?obj rdfs:comment ?text . FILTER (lang(?text) = 'es')


       ?obj ecrm:P65_shows_visual_item ?visual_item .

                  FILTER ((?visual_item = <http://data.silknow.org/vocabulary/743>) ||

                        (?visual_item = <http://data.silknow.org/vocabulary/744>) ||

                        (?visual_item = <http://data.silknow.org/vocabulary/745>) ||



                        (?visual_item = <http://data.silknow.org/vocabulary/768>) ||

                        (?visual_item = <http://data.silknow.org/vocabulary/750>) ||
                        (?visual_item = <http://data.silknow.org/vocabulary/765>) ||
                        (?visual_item = <http://data.silknow.org/vocabulary/793>) ||
                        (?visual_item = <http://data.silknow.org/vocabulary/785>) ||
                        (?visual_item = <http://data.silknow.org/vocabulary/824>) ||
                        (?visual_item = <http://data.silknow.org/vocabulary/759>))



FILTER (?museum = <http://data.silknow.org/graph/imatex> || 
        ?museum = <http://data.silknow.org/graph/garin> || 
        ?museum = <http://data.silknow.org/graph/cer> )


}
ORDER BY ?museum
