prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>
prefix silk:   <http://data.silknow.org/ontology/property/>

SELECT DISTINCT ?obj ?museum ?text ?material_group 

WHERE {
  GRAPH ?museum {
  
      ?prod ecrm:P108_has_produced ?obj .
      ?obj a ecrm:E22_Man-Made_Object . }
{
      ?obj rdfs:comment ?text }


        ?prod ecrm:P126_employed ?x .
                 ?material_group skos:member ?x FILTER contains(str(?material_group), "facet")  
 

FILTER (contains(str(?museum), "vam") || 
        contains(str(?museum), "risd") || 
        contains(str(?museum), "artic") || 
        contains(str(?museum), "met") || 
        contains(str(?museum), "mfa") || 
        contains(str(?museum), "smithsonian") )



}
ORDER BY ?museum
