prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>
prefix silk:   <http://data.silknow.org/ontology/property/>

SELECT DISTINCT ?obj ?museum ?text ?depict_group 

WHERE {
  GRAPH ?museum {
  
      ?prod ecrm:P108_has_produced ?obj .
      ?obj a ecrm:E22_Man-Made_Object . }
{
      ?obj rdfs:comment ?text . FILTER (lang(?text) = 'es') }

      ?obj ecrm:P65_shows_visual_item  ?z .
                ?depict_group skos:member ?z FILTER contains(str(?depict_group), "facet")
               
               

FILTER (?museum = <http://data.silknow.org/graph/imatex> || 
        ?museum = <http://data.silknow.org/graph/garin> || 
        ?museum = <http://data.silknow.org/graph/cer> )



}
ORDER BY ?museum
